language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode10.1
      env: TARGET_OS=ios
    - os: linux
      sudo: required
      compiler: gcc
      services:
        - docker
    - os: linux
      sudo: required
      compiler: gcc
      services:
        - docker
      env: TARGET_OS=android

script:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./scripts/build.sh; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker pull ubuntu:18.10; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run -i -e TRAVIS=$TRAVIS -t -v $PWD:/libwebrtc ubuntu:18.10 bash /libwebrtc/scripts/build.sh; fi

deploy:
  - provider: releases
    api_key:
      secure: ZCpMHUplpo32XRMy8mjO2LzXB7UeMdBo1DpphwQBtl9FKeqU2V1ACsenrl3pQciCL7iecGaX3a/u2IQY7QT+GHKh3H1ZKeEoZ21GvGVP5eu90+r5z/5Z1nfol7F6a1EdkWI+flflH4DUNSuatIsKP5tP3HuHsDM0/sxmbX4dFty8c5cGG7RsBd6MSa4iaphIwLl67GoSHgDID92OA0xL9nr5jQWu6FyqEEzVCGItWDtx2nspwRQaJ4UYbByt5KLAwuhMCrXDdFvnfQmVVh4ugD+1GAayQ/+D5N3lObQKmDKFHxcGEwu1nI9Nc3TgHyyrzHlY98tk5bN/vQ1jWyfYVjyxnOqtz+KzDC4dktlUcEIDJEFtvodCzHcy3VknFvxv/14YyamF5BGj7LVShVLfIEF9+JOoEqwamu1I4cr/wxWNUKpIvG3LuSvJPBaV2QCrG7iogSJURPuh//mnQFxoRWbMIOh/zElNsLRPqm+ONQ68FYKsFEovVCUTo0iHb/FkoUpRkbTPEOq6raHFH3rizjrk2PSiSAU7QQneJW/Spcqki7Kx2NWww9Oee3FZT+CacoJYQDw+7qCtCPnAhPIiNA//OSaTayOSVxkxJw/YZFiSKwmce/z7VLJxTm/Vfl7SbW6B2sP8qH5UrS/PB7wNh3uD1mVkvi4qI/LBCoEIXXY=
    file_glob: true
    file: build/zips/*
    skip_cleanup: true
    on:
      tags: true
